#!/usr/bin/env python3
"""Build site/content-bundle.js from structured modular content in site/content/.

This compiles individual day articles and week intros into a single JavaScript
bundle so site/index.html remains lightweight (<30 KB) while maintaining 100%
compatibility with file:// URLs (no CORS/fetch restrictions) and GitHub Pages.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = ROOT / "site" / "content"
DAYS_DIR = CONTENT_DIR / "days"
WEEKS_DIR = CONTENT_DIR / "weeks"
BUNDLE_OUTPUT = ROOT / "site" / "content-bundle.js"


def build_bundle():
    articles = {}
    if DAYS_DIR.exists():
        for file in sorted(DAYS_DIR.glob("day-*.html")):
            # slug e.g. "0-1" from "day-0-1.html" or "1" from "day-1.html"
            slug = file.stem[4:]
            articles[slug] = file.read_text(encoding="utf-8").strip()

    intros = {}
    if WEEKS_DIR.exists():
        for file in sorted(WEEKS_DIR.glob("week-*.html")):
            # week num e.g. "0" from "week-0.html"
            week_num = file.stem[5:]
            intros[week_num] = file.read_text(encoding="utf-8").strip()

    payload = (
        "// Auto-generated by scripts/build_site.py — do not edit directly.\n"
        "// Edit individual files in site/content/days/ and site/content/weeks/.\n"
        f"window.COURSE_ARTICLES = {json.dumps(articles, indent=2)};\n\n"
        f"window.WEEK_INTROS = {json.dumps(intros, indent=2)};\n"
    )

    BUNDLE_OUTPUT.write_text(payload, encoding="utf-8")
    print(f"Built {BUNDLE_OUTPUT} ({len(articles)} articles, {len(intros)} week intros, {BUNDLE_OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    build_bundle()
